package com.github.lua.events

enum class SpigotEvents {
    BlockBreakEvent,
    BlockBurnEvent,
    BlockCanBuildEvent,
    BlockCookEvent,
    BlockDamageAbortEvent,
    BlockDamageEvent,
    BlockDispenseArmorEvent,
    BlockDispenseEvent,
    BlockDropItemEvent,
    BlockExpEvent,
    BlockExplodeEvent,
    BlockFadeEvent,
    BlockFertilizeEvent,
    BlockFormEvent,
    BlockFromToEvent,
    BlockGrowEvent,
    BlockIgniteEvent,
    BlockMultiPlaceEvent,
    BlockPhysicsEvent,
    BlockPistonEvent,
    BlockPistonExtendEvent,
    BlockPistonRetractEvent,
    BlockPlaceEvent,
    BlockReceiveGameEvent,
    BlockRedstoneEvent,
    BlockShearEntityEvent,
    BlockSpreadEvent,
    CauldronLevelChangeEvent,
    EntityBlockFormEvent,
    FluidLevelChangeEvent,
    LeavesDecayEvent,
    MoistureChangeEvent,
    NotePlayEvent,
    SignChangeEvent,
    SpongeAbsorbEvent,
    EnchantItemEvent,
    PrepareItemEnchantEvent,
    AreaEffectCloudApplyEvent,
    ArrowBodyCountChangeEvent,
    BatToggleSleepEvent,
    CreatureSpawnEvent,
    CreeperPowerEvent,
    EnderDragonChangePhaseEvent,
    EntityAirChangeEvent,
    EntityBreakDoorEvent,
    EntityBreedEvent,
    EntityChangeBlockEvent,
    EntityCombustByBlockEvent,


    InventoryClickEvent,
    InventoryCloseEvent,
    InventoryOpenEvent,
    InventoryInteractEvent,


    PlayerJoinEvent,
    PlayerQuitEvent
}